name: Plexify

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get current version
        id: vars
        run: echo ::set-output name=version::$(cat VERSION)

      - name: Commit and push version increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Increment version" -a
          git push

      - name: Build and Push Docker Image
        run: |
          docker buildx build --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/plexify:${{ steps.vars.outputs.version }} \
          --tag ${{ secrets.DOCKER_USERNAME }}/plexify:latest \
          --push .

      - name: Run Docker Image
        run: |
          docker run -d --name plexify ${{ secrets.DOCKER_USERNAME }}/plexify:${{ steps.vars.outputs.version }}

      - name: Test Docker Image
        run: |
          docker exec plexify /bin/sh -c "echo \"I'm running...\""
