name: ci Plexify

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to release (e.g., 1.1.1)'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please (semantic versioning & release notes)
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          command: ${{ github.event_name == 'workflow_dispatch' && 'release' || 'release-pr' }}
          version: ${{ github.event.inputs.version }}

  docker:
    needs: release
    if: ${{ needs.release.outputs.release_created == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nyancod3r/plexify:latest
            nyancod3r/plexify:${{ needs.release.outputs.tag_name }}
          build-args: |
            RELEASE_VERSION=${{ needs.release.outputs.tag_name }}

      - name: Test 
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: |
          docker run --rm --name test \
          -e SPOTIFY_CLIENT_ID -e SPOTIFY_CLIENT_SECRET \
          nyancod3r/plexify:${{ needs.release.outputs.tag_name }} python -m unittest discover -s tests -v