name: Plexify

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker Image
        run: docker buildx build --file Dockerfile --tag nyancod3r/plexify:latest .

      - name: Run Docker Image
        run: |
          docker run -d --name plexify nyancod3r/plexify:latest
      - name: Test Docker Image
        run: |
          docker exec plexify curl -I https://google.com      

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker tag plexify:latest ${{ secrets.DOCKER_USERNAME }}/plexify:v${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/plexify:v${{ github.run_number }}
