name: Plexify

on:
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Get current version
        id: vars
        run: |
          if [ -s VERSION ]; then
            echo "version=$(cat VERSION)" >> $GITHUB_ENV
          else
            echo "version=1.0" >> $GITHUB_ENV
          fi

      - name: Print current version
        run: echo "Current version is ${{ env.version }}"

      - name: Increment version
        run: echo $(echo "${{ env.version }} + 0.1" | bc) | tee VERSION

      - name: Update version in environment
        run: echo "version=$(cat VERSION)" >> $GITHUB_ENV

      - name: Commit and push version increment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add VERSION
          git commit -m "Increment version"
          git push

      - name: Build and Push Docker Image
        run: |
          docker buildx build --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/plexify:${{ env.version }} \
          --tag ${{ secrets.DOCKER_USERNAME }}/plexify:latest \
          --push .

      - name: Run Docker Image
        run: |
          docker run -d --name plexify ${{ secrets.DOCKER_USERNAME }}/plexify:${{ env.version }}

      - name: Test Docker Image
        run: |
          docker exec plexify /bin/sh -c "echo \"I'm running...\""