name: Plexify

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker buildx build --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/plexify:v${{ github.run_number }} --push .

      - name: Run Docker Image
        run: |
          docker run -d --name plexify ${{ secrets.DOCKER_USERNAME }}/plexify:v${{ github.run_number }}

      - name: Test Docker Image
        run: |
          docker exec plexify curl -I https://google.com
