name: ci Plexify

on:
  release:
    types: [created]
    branches:
      - master

env:
  TEST_TAG: nyancod3r/plexify:test
  LATEST_TAG: nyancod3r/plexify:latest
  VERSION_TAG: nyancod3r/plexify:${{ github.event.release.tag_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}

      - name: Test
        run: |
          docker run --rm --name test \
          ${{ env.TEST_TAG }}

      - name: Build and push latest
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}
          
      - name: Build and push version
        if: success()
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.VERSION_TAG }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}