name: ci Plexify

on:
  push:
    branches:
      - '*'
  release:
    types: [created]
    branches:
      - master

env:
  TEST_TAG: nyancod3r/plexify:test
  LATEST_TAG: nyancod3r/plexify:latest
  VERSION_TAG: nyancod3r/plexify:${{ github.event.release.tag_name }}

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and export to Docker
        if: github.ref != 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./src
          load: true
          tags: ${{ env.TEST_TAG }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}

      - name: Test
        if: github.event_name != 'release' && github.ref != 'refs/heads/main'
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: |
          docker run --rm --name test \
          -e SPOTIPY_CLIENT_ID -e SPOTIPY_CLIENT_SECRET \
          ${{ env.TEST_TAG }} python -m unittest discover -s tests -v

      - name: Build and push latest
        if: github.event_name == 'release' && github.event.release.prerelease == false
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.LATEST_TAG }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}
          
      - name: Build and push version
        if: github.event_name == 'release'
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.VERSION_TAG }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}