name: ci Plexify

on:
  push:
    branches:
      - '*'
  release:
    types: [created]
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release Please (semantic versioning & release notes)
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple

  docker:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12, 3.13]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./src
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            nyancod3r/plexify:latest
            nyancod3r/plexify:${{ github.event.release.tag_name }}
          build-args: |
            RELEASE_VERSION=${{ github.event.release.tag_name }}

      - name: Test
        env:
          SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
          SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        run: |
          docker run --rm --name test \
          -e SPOTIPY_CLIENT_ID -e SPOTIPY_CLIENT_SECRET \
          nyancod3r/plexify:${{ github.event.release.tag_name }} python -m unittest discover -s tests -v